# Generated by Django 5.1.5 on 2025-08-31 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0002_alter_order_quantity_alter_order_total_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='production_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
