# Generated by Django 5.1.5 on 2025-09-01 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0003_order_confirmed_product_production_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='production_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
