# Generated by Django 5.1.5 on 2025-09-01 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0004_alter_product_production_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='instock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
