# Generated by Django 5.1.5 on 2025-09-01 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0005_product_instock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='production_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
